name = "aiken-lang/fracada"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/fracada'"

[repository]
user = "aiken-lang"
project = "fracada"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
