const BLOCKFROST_API_URL = process.env.NEXT_PUBLIC_BLOCKFROST_API_URL || '';
const BLOCKFROST_PROJECT_ID = process.env.NEXT_PUBLIC_BLOCKFROST_PROJECT_ID || '';
const NETWORK_NAME = process.env.NEXT_PUBLIC_NETWORK_NAME || 'Preprod';
// const IS_TESTNET = NETWORK_NAME !== 'Mainnet';

export { BLOCKFROST_API_URL, BLOCKFROST_PROJECT_ID, NETWORK_NAME };